// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRY832l12bhmE3nshUVhOpChYmClLrIo',
    appId: '1:872443148627:android:29f409e219e209b089c9a6',
    messagingSenderId: '872443148627',
    projectId: 'ecommerceapp-8d45a',
    storageBucket: 'ecommerceapp-8d45a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqRcwIipSdt1ahwnRYZzFsBKW5jkUZ_I',
    appId: '1:872443148627:ios:2f2ae0b4f9c1554689c9a6',
    messagingSenderId: '872443148627',
    projectId: 'ecommerceapp-8d45a',
    storageBucket: 'ecommerceapp-8d45a.firebasestorage.app',
    androidClientId: '872443148627-q4cpp2v45iik9nvlui1urjtvpp1i6qfj.apps.googleusercontent.com',
    iosClientId: '872443148627-q18m2gao764nlcge7n33bjq20laaf7np.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

}